service: sqs-lambda-b-receive-msg

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:ReceiveMessage"
      Resource: arn:aws:sqs:us-east-1:XXXXXXXXXXX:PendingTestQueue
    - Effect: "Allow"
      Action:
        - "sqs:DeleteMessage"
      Resource: arn:aws:sqs:us-east-1:XXXXXXXXXXX:PendingTestQueue

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-offline

custom:
  prune:
    automatic: true
    number: 1

functions:
  ReceiveMecrchant:
    handler: src/handler.receiveQueue
    events:
      - http:
          method: get
          path: receiveQueue
          cors: true
